language: ruby
sudo: false
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
bundler_args: "--no-deployment"
script:
   - echo $BUNDLE_GEMFILE
   - bundle exec rake
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.3
  - 2.3.1
notifications:
  email: false
